services:
  - type: web
    name: fortifund-ml-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PORT
        value: 8000
